<a href="https://colab.research.google.com/github/HISATAKA-KATO/EU_M_Math-Repository/blob/main/Chap05_Ex_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#今回利用するライブラリ
import numpy as np
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame
import numpy.random as random

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
sns.set_style()
%matplotlib inline

#小数点第三位まで表示
%precision 3

#ランダムシード
np.random.seed(0)

#zipダウンロードライブラリ
import requests, zipfile
from io import StringIO
import io

In [6]:
sample_multi_array_data2 = np.arange(16).reshape(4,4)
sample_multi_array_data2

print('すべての要素の平方根：\n', np.sqrt(sample_multi_array_data2))


すべての要素の平方根：
 [[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]
