<a href="https://colab.research.google.com/github/HISATAKA-KATO/EU_M_Math-Repository/blob/main/Chap02_Ex_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 以下にライブラリを定義する。
import numpy as np
import numpy.random as random
import scipy as sp
import scipy.linalg  as linalg  ##行列式用
import pandas as pd
from pandas import Series, DataFrame


# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 少数第3位まで表示
%precision 3

'%.3f'

In [2]:
A = np.array([1,2,3,1,3,2,3,1,2]).reshape(3,3)
print('行列A:\n',A)
print('逆行列:\n',linalg.inv(A))
print('固有値:\n',linalg.eig(A))

行列A:
 [[1 2 3]
 [1 3 2]
 [3 1 2]]
逆行列:
 [[-0.333  0.083  0.417]
 [-0.333  0.583 -0.083]
 [ 0.667 -0.417 -0.083]]
固有値:
 (array([ 6.   +0.j, -1.414+0.j,  1.414+0.j]), array([[-0.577, -0.722,  0.16 ],
       [-0.577, -0.143, -0.811],
       [-0.577,  0.677,  0.563]]))
