<a href="https://colab.research.google.com/github/HISATAKA-KATO/EU_M_Math-Repository/blob/main/Chap05_Ex_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
#今回利用するライブラリ
import numpy as np
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#可視化ライブラリ
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style()
%matplotlib inline

#小数点第三位まで表示
%precision 3

#ランダムシード
np.random.seed(0)

#zipダウンロードライブラリ
import requests, zipfile
from io import StringIO
import io


In [19]:
#data prepare
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)

b_data = data[sample_names == 'b']

print(sample_names  == 'b')
print(sample_names)
print(b_data)
print(data)

[False  True False False False]
['a' 'b' 'c' 'd' 'a']
[[-0.977  0.95  -0.151 -0.103  0.411]]
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]
