<a href="https://colab.research.google.com/github/HISATAKA-KATO/EU_M_Math-Repository/blob/main/Chap02_Ex_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# 以下にライブラリを定義する。
import numpy as np
import numpy.random as random
import scipy as sp
import scipy.linalg  as linalg
import pandas as pd
from pandas import Series, DataFrame


# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 少数第3位まで表示
%precision 3

'%.3f'

In [8]:
A = np.array([1,2,3,1,3,2,3,1,2]).reshape(3,3)
print('行列A:\n',A)
print('行列式:',linalg.det(A))

行列A:
 [[1 2 3]
 [1 3 2]
 [3 1 2]]
行列式: -12.0
